name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - pandas
  - matplotlib
  - flask
  - dash
  - keras
  - pyspark
  - scikit-learn
  - scipy
  - seaborn
  - sqlite
  - tensorflow
  - IPython
  - pillow
